import { EventEmitter, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { BrOption, BrRadioConfig } from '../../models/controls-config.model';
import { CustomRadioInput, MaterialRadioInput, PrimeRadioInput } from '../../adapters/radio.adapter';
import { RuntimeUiConfigService } from '../../services/runtime-ui-config.service';
import { BaseValueAccessor } from '../../forms/base-value-accessor';
import { BrControlEvent } from '../../models/control-event.model';
import { ControlRegistryService } from '../../services/control-registry.service';
import * as i0 from "@angular/core";
export declare class BrRadioComponent extends BaseValueAccessor<any> implements OnInit, OnChanges, OnDestroy {
    private readonly runtimeUiConfig;
    private readonly controlRegistry;
    config?: BrRadioConfig;
    id?: string;
    controlId?: string;
    name?: string;
    className?: string;
    value?: any;
    options?: BrOption[];
    disabled?: boolean;
    required?: boolean;
    label?: string;
    meta?: Record<string, any>;
    showLibraryTag: boolean;
    valueChange: EventEmitter<any>;
    blur: EventEmitter<FocusEvent>;
    focus: EventEmitter<FocusEvent>;
    input: EventEmitter<Event>;
    change: EventEmitter<Event>;
    keydown: EventEmitter<KeyboardEvent>;
    keyup: EventEmitter<KeyboardEvent>;
    click: EventEmitter<MouseEvent>;
    controlEvent: EventEmitter<BrControlEvent<any>>;
    mode: 'CUSTOM' | 'MATERIAL' | 'PRIMENG';
    customConfig: CustomRadioInput;
    materialConfig: MaterialRadioInput;
    primeConfig: PrimeRadioInput;
    private readonly destroy$;
    private registryHandle?;
    constructor(runtimeUiConfig: RuntimeUiConfigService, controlRegistry: ControlRegistryService);
    ngOnInit(): void;
    ngOnChanges(_: SimpleChanges): void;
    ngOnDestroy(): void;
    onImplementationValueChange(value: any): void;
    onImplementationBlur(event: FocusEvent): void;
    onImplementationFocus(event: FocusEvent): void;
    onImplementationInput(event: Event): void;
    onImplementationChange(event: Event): void;
    onImplementationKeydown(event: KeyboardEvent): void;
    onImplementationKeyup(event: KeyboardEvent): void;
    onImplementationClick(event: MouseEvent): void;
    protected normalizeValue(value: any): any;
    protected afterWriteValue(value: any): void;
    protected afterDisabledStateChange(isDisabled: boolean): void;
    private adaptConfig;
    private resolveConfig;
    private get effectiveId();
    private refreshRegistryRegistration;
    private extractClasses;
    private emitControlEvent;
    static ɵfac: i0.ɵɵFactoryDeclaration<BrRadioComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<BrRadioComponent, "br-radio", never, { "config": { "alias": "config"; "required": false; }; "id": { "alias": "id"; "required": false; }; "controlId": { "alias": "controlId"; "required": false; }; "name": { "alias": "name"; "required": false; }; "className": { "alias": "className"; "required": false; }; "value": { "alias": "value"; "required": false; }; "options": { "alias": "options"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "required": { "alias": "required"; "required": false; }; "label": { "alias": "label"; "required": false; }; "meta": { "alias": "meta"; "required": false; }; "showLibraryTag": { "alias": "showLibraryTag"; "required": false; }; }, { "valueChange": "valueChange"; "blur": "blur"; "focus": "focus"; "input": "input"; "change": "change"; "keydown": "keydown"; "keyup": "keyup"; "click": "click"; "controlEvent": "controlEvent"; }, never, never, true, never>;
}
