import { EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { GridShellInput } from '../../../adapters/grid.adapter';
import { BrGridAction, BrGridActionEvent, BrGridColumnOption, BrGridFilterRule, BrGridSortRule } from '../../../models/grid-config.model';
import * as i0 from "@angular/core";
interface GridRow {
    __rowId: number;
    __raw: any;
}
export declare class GridShellComponent implements OnChanges {
    config: GridShellInput;
    variant: 'custom' | 'material' | 'canvas';
    action: EventEmitter<BrGridActionEvent>;
    allColumns: GridShellInput['columns'];
    availableColumns: BrGridColumnOption[];
    visibleColumnFields: string[];
    rows: GridRow[];
    pageRows: GridRow[];
    selectedRowIds: Set<number>;
    searchOpen: boolean;
    searchTerm: string;
    zoomMode: boolean;
    showSortModal: boolean;
    showFilterModal: boolean;
    sortCriteria: BrGridSortRule[];
    filterCriteria: BrGridFilterRule[];
    showColumnsPanel: boolean;
    showPrimaryActionMenu: boolean;
    columnSearch: string;
    showContextMenu: boolean;
    contextX: number;
    contextY: number;
    contextRowId: number | null;
    currentPage: number;
    pageSize: number;
    totalPages: number;
    totalRows: number;
    pageSizeOptions: number[];
    get rootClasses(): string[];
    get rootStyles(): Record<string, string>;
    get isCustomVariant(): boolean;
    get isMaterialVariant(): boolean;
    get isCanvasVariant(): boolean;
    get activeSortCount(): number;
    get activeFilterCount(): number;
    get activeColumns(): GridShellInput['columns'];
    get filteredColumnOptions(): BrGridColumnOption[];
    get selectionCount(): number;
    get isAllPageSelected(): boolean;
    get isSomePageSelected(): boolean;
    get startItem(): number;
    get endItem(): number;
    ngOnChanges(changes: SimpleChanges): void;
    onDocumentClick(): void;
    openSortModal(event: MouseEvent): void;
    closeSortModal(): void;
    openFilterModal(event: MouseEvent): void;
    closeFilterModal(): void;
    applySortCriteria(): void;
    clearSortCriteria(): void;
    applyFilterCriteria(): void;
    clearFilterCriteria(): void;
    toggleSearch(): void;
    toggleZoomMode(): void;
    onSearchChange(): void;
    refreshGrid(): void;
    openColumnsPanel(event: MouseEvent): void;
    closeColumnsPanel(): void;
    togglePrimaryActionMenu(event: MouseEvent): void;
    toggleColumn(field: string): void;
    removeColumn(field: string): void;
    moveColumn(field: string, direction: -1 | 1): void;
    toggleSelectAllOnPage(checked: boolean): void;
    toggleRowSelection(rowId: number, checked: boolean): void;
    clearSelection(): void;
    onRowContextMenu(event: MouseEvent, rowId: number): void;
    openContextMenuFromButton(event: MouseEvent, rowId: number): void;
    closeContextMenu(event: MouseEvent): void;
    getCellValue(row: GridRow, field: string): string;
    getColumnHeader(field: string): string;
    getColumnGroup(field: string): string;
    trackByRow(_: number, row: GridRow): number;
    trackByField(_: number, field: string): string;
    trackByAction(_: number, action: BrGridAction): string;
    setPageSize(value: number): void;
    nextPage(): void;
    prevPage(): void;
    firstPage(): void;
    lastPage(): void;
    onToolbarPrimaryClick(): void;
    onToolbarPrimaryMenuAction(action: BrGridAction): void;
    onSelectionActionClick(action: BrGridAction): void;
    onContextActionClick(action: BrGridAction): void;
    saveColumns(): void;
    private emitSelectionChange;
    private getSelectedRows;
    private emitAction;
    private seedSortCriteria;
    private seedFilterCriteria;
    private applyView;
    static ɵfac: i0.ɵɵFactoryDeclaration<GridShellComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<GridShellComponent, "br-grid-shell", never, { "config": { "alias": "config"; "required": false; }; "variant": { "alias": "variant"; "required": false; }; }, { "action": "action"; }, never, never, true, never>;
}
export {};
